name: code_lint_build_repeat

on:
  push:
    paths-ignore:
      - '.helm/**'
      - 'config.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.helm/**'
      - 'config.yml'
      - 'README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://golangci/golangci-lint:v1.30.0
      with:
        args: golangci-lint run -v --timeout=3m
      env:
        CGO_ENABLED: 0

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.x
    - name: Login to the Docker Registry
      run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



