name: goreleaser

on:
  push:
    paths-ignore:
      - '.helm/**'
      - 'config.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.helm/**'
      - 'config.yml'
      - 'README.md'

permissions:
  contents: write
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: golangci/golangci-lint-action@v6
      # with:
      #   only-new-issues: true

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
